type Blob {
  id: Int!
  title: String
  body: String
  created_at: String!
  updated_at: String!
}

type Query {
  BlobList: [Blob]
}

type Mutation {
  BlobCreate(body: String, title: String): Blob
  BlobUpdate(id: Int!, body: String, title: String): Blob
  BlobDelete(id: Int!): Int!
}

type Subscription {
  BlobCreated: Blob
  BlobUpdated: Blob
  BlobDeleted: Int!
}
